name: Slither Scheduled Security Scan

on:
  schedule:
    - cron: '0 4 * * 1' # Every Monday at 04:00 UTC
  workflow_dispatch:

jobs:
  slither-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Slither
        run: |
          python -m pip install --upgrade pip
          pip install slither-analyzer
      - name: Run Slither (JSON)
        run: |
          slither src/ --json slither-scan.json --filter-paths test/ || true
      - name: Parse Slither JSON
        run: |
          python3 scripts/ci/parse_slither.py slither-scan.json slither-scan-parsed.json slither-scan-summary.md || true
      - name: Upload scan results
        uses: actions/upload-artifact@v4
        with:
          name: slither-scan-results
          path: |
            slither-scan.json
            slither-scan-parsed.json
            slither-scan-summary.md
